inherit_from: .rubocop_todo.yml

Gemspec/DeprecatedAttributeAssignment:
  Enabled: true

AllCops:
  NewCops: enable
  Exclude:
    - 'db/schema.rb'

Style/Documentation:
  Enabled: false

Lint/ClassAndModuleChildren:
  Enabled: false
